templates/html/.helpers/handlebars.js, templates/html/.partials/content.html, templates/html/.partials/info.html, templates/html/.partials/message.html, templates/html/.partials/messages.html, templates/html/.partials/operation.html, templates/html/.partials/parameters.html, templates/html/.partials/schema-prop.html, templates/html/.partials/schema.html, templates/html/.partials/schemas.html, templates/html/.partials/security.html, templates/html/.partials/tags.html, templates/html/.partials/topic.html, templates/html/.partials/topics.html, templates/html/css/main.css, templates/html/index.html
It adds a template for HTML documentation generation. The template is exactly the same you can find at https://github.com/asyncapi/docgen.
The idea is to migrate both, `docgen` and `node-codegen`, to this package because it provides much more flexibility and we'll have to maintain only one package.
=> Add HTML template (from asyncapi-docgen package)

README.md, lib/generator.js
It adds:
We need to be able to programmatically use this module in the editor.
=> Add getTemplateFile and generateTemplateFile functions

templates/markdown/.partials/messages.md
The TOC item is not shown, but the header was still in the markdown file. This PR makes it consistent.
=> Don't show "messages" header if there are no messages defined.

templates/markdown/.partials/info.md, templates/markdown/.partials/security.md, templates/markdown/.partials/tags.md, templates/markdown/.partials/topic.md
The markdown generated is pretty dirty as it has a lot of HTML markup in the files. It makes the temples prone to errors as HTML is more complex (see #9) and can have side effects with some markdown tooling (see #12). Additionally, there are CSS classes all over the place, which can easily be replaced with simple CSS element selectors. Also, list of tags for example can easily be represented as lists for example, instead of nested divs. So this is my proposal to clean things up and simplify the markdown templates.
=> Clean-up HTML / Markdown

templates/markdown/.partials/message.md, templates/markdown/.partials/topic.md
Markdown template: I replaced the HTML headings with pure markdown for two reasons:
1. Markdown should contain as much markdown as possible instead of HTML.
2. If you use documentation generators for markdown such as MkDocs, it will fail to generate good table of contents as it is missing all the HTML headings. This leads to a not very useful TOC such as:
```
Table of Contents
Topics
Message
Payload
Example
Message
Payload
Example
Message
Payload
Example
Message
Payload
Example
Message
Payload
Example
...
```
=> Pure markdown headings

lib/parser.js, package.json
instead of logging errors silently, I'm changing to the parser to re-throw errors to clients. 
NOTE: I'm not sure if this will break others libraries making use of the generator: that would be the case if not doing error handling correctly.
ALSO: I'm sending this directly to Master as fran mentioned we are using from now github flow
=> change parser to throw errors to callers and increment generator version

cli.js
Changes the output message from referencing "shiny new API documentation" to "shiny new generated files".
=> fix [cli]: not all output is API documentation

templates/html/.partials/message.html, templates/html/.partials/operation.html, templates/html/.partials/schema.html, test/docs/array_example.yml
I ran all given tests (including the one I added) before and after changes, and checked outputs with kdiff. This only touches the html template. Hopefully this commit PR is OK, I realize that I kind of just appeared out from nowhere!
=> #25 operation and message templates hide schema example and show formatted example

templates/html/.partials/schema-prop.html
Both pattern and the values of the enum array are case-sensitive. There shouldn't be a lowercase class on them.
=> Removed lowercase class from case-sensitive property values

templates/html/.partials/schema-prop.html
It seems support for these keywords is missing.
https://json-schema.org/understanding-json-schema/reference/generic.html
Also, the default value was not stringified so null looked like this:
```Default:```
instead of this:
```Default: null```
As an added bonus strings and numbers can be differentiated.
I'll open an additional PR in openapi-sampler to support const and examples in the generated payload snippet.
=> Support generic keywords examples and const from draft 6

templates/html/.partials/sidebar.html
Implementation of the functionality discussed in the following issue: https://github.com/asyncapi/generator/issues/69
Users can choose to use tags for structure in the sidebar using the following command:
`ag asyncapi.yaml html --params '{"sidebarOrganization":"hierarchical"}'`
This will list the tags in the sidebar and categorize each operation under the appropriate tag. The tags are clickable and clicking one will show the entire list of operations under that specific tag.
=> Implementation of tags in the sidebar

README.md, lib/generator.js, templates/html/.partials/sidebar.html, test/docs/streetlights.yml
Passing 'params' on to use it with .generateTemplateFile() as a follow-up to issue #69. Also adding a short description and tags to the streetlights Example for demonstration purposes of the sidebarOrganization param.
=> Passing 'params' on from generateTemplateFile()

templates/html/.partials/schema-prop.html
=> HTML Doc: Fix pattern case

Dockerfile, README.md, dockerboot.sh
FYI @treeder and @YBogomolov. I already pushed this image to Docker Hub. It's tagged with `latest` and `0.10.0`.
It removes the need for `asyncapi-node-codegen` as the current generator already supports Node.js.
=> Fix Docker docs

API.md, README.md, cli.js, lib/generator.js, package-lock.json, package.json
```
Usage: ag [options] <asyncapi> <template>
Options:
-V, --version                  output the version number
-o, --output <outputDir>       directory where to put the generated files (defaults to current directory) (default: /Users/fmvilas/www/asyncapi-generator)
->    -d, --disable-hook <hookName>  disable a specific hook
->    -n, --no-overwrite <glob>      glob or path of the file(s) to skip when regenerating
-p, --param <name=value>       additional param to pass to templates
-t, --templates <templateDir>  directory where templates are located (defaults to internal templates directory) (default: null)
-h, --help                     output usage information
```
1. Added hooks functionality. So far there's only one hook point: `generate:after`. Hooks are custom functions you can run …
=> Add hooks and no-overwrite option

API.md, lib/generator.js, templates/html/.partials/content.html, templates/html/.partials/example.html, templates/html/.partials/message.html, templates/markdown/.partials/content.md, templates/markdown/.partials/schema-prop.md
Add a new option to choose between the output of the generation process between `fs` (filesystem) or `string`. The latter can be chosen only when `entrypoint` is set.
=> Add output type: fs or string

lib/generator.js
A first step to generate message definition files (like Avro files) is to allow generate a file for each message in the AsyncAPI definition.
As it's done for channels, with this PR the generator allows use $$message$$ in the file name of a file to generate message files.
=> Generate messages files

templates/html/.filters/all.js, templates/html/.partials/schema-prop.html, templates/markdown/.partials/schema-prop.md
Adding 'allOf' schema type support in markdown and HTML following the pattern of 'anyOf' and 'oneOf'.
Additionally, in markdown, it was displaying `undefined` in the name column of the payload table for each element in the allOf/anyOf/oneOf, and I changed it to display `<1>` or `<2>` etc.
=> allOf schema support for markdown and HTML

templates/html/.filters/all.js, templates/html/.partials/schema-prop.html
Latest releases are showing the `x-parser-*` extensions. These extensions are for tooling creators and are of no interest for the consumer.
Thanks to Scott Popplewell for reporting.
=> Do not show parser extensions

templates/nodejs/config/common.yml
This option was already there but was not in the config file. It's useful when you're using free instances of cloud brokers, where the vendor usually prepend your username to every topic. I'm leaving it empty so, by default, it's not taken into account but it's possible to override the value from a `.env` file and access it like `config.broker.kafka.topicPrefix`.
`qw7yecbj` is my username and it prepends `qw7yecbj-` to every topic.
=> Add topicPrefix to Nodejs config file

templates/nodejs/.filters/all.js, templates/nodejs/src/api/index.js, templates/nodejs/src/api/routes/$$channel$$.js, test/docs/streetlights.yml
After the change we did yesterday to "filenamify" file names, routes and handlers requires were broken.
Also, I'm taking the opportunity to remove server url variables, which is not yet supported by the generator. I created a different issue here: https://github.com/asyncapi/generator/issues/182.
=> Fix wrong require statements

templates/html/.partials/schema-prop.html, templates/html/css/main.css
This fixes an issue where the centered content might overlap the examples on the right on medium-sized screens (15").
It also removes the `Example` section within the schema/payload block, as this information is duplicated anyway by the examples on the right.
**Before**
**After**
=> Fix content overlapping examples

templates/html/.partials/schema-prop.html, templates/html/.partials/type.html
This PR fixes a bug that's happening when a Schema object of type `array` contains an `items` property which itself is an array.
An example to reproduce the bug:
```yaml
asyncapi: 2.0.0
info:
title: Test
version: 1.0.0
channels:
test:
publish:
message:
payload:
type: array
items:
- type: object
```
The reason is that `items` can be either an array of objects or an object.
=> Fix bug in array items

lib/generator.js
`$$schema$$` is producing a file for each schema, including parameters, headers, etc. That's not the desired behavior therefore, this PR makes `$$schema$$` generate a file for each schema defined under the components section.
To achieve the same behavior as before, you can use `$$everySchema$$`.
Fixes #213
=> Add $$everySchema$$ to replace $$schema$$

.github/workflows/main.yml, Dockerfile, Makefile, README.md, package.json, release.sh
GitHub Action that published docker image will be triggered on a new tag creation.
- changed base image in dockerfile to alpine version which makes image much smaller and is enough, and still official node image. Instead of 937MB it is 145MB now on local
- added license to package.json as npm didn't like it is missing
- added example of running docker on local to README.md
- sorry for badges but I'm just a huge fan....can remove if you do not like them...
- cleaned up makefile and release.sh
- GitHub action is very simple as most of the work was already done in scripts that I reused. I decided to keep flow with scripts instead of specific GitHub Action as I think having scripts in a repo is great if you have to push from local, and best if the same scripts are also used in CI
- echoing …
=> Cleanup setup of docker and add automated publishing

templates/html/css/main.css
When using the HTML template on a dark background browser, the background color is not white but "dark" and the template doesn't look great. This PR provides a sane default for background and links.
Fixes https://github.com/asyncapi/vscode-extension/issues/1
=> Set sane CSS defaults on the HTML template

lib/generator.js
I started using this feature because I started working on latest master for another issue....and I got annoyed that there is no support for case:
_I have a git repo and my output directory is in .gitignore which mean no harm if generator generates files there_
=> Add support for gitignore to git protection feature

AUTHORING.md
Stumbled upon it when I went through another PR, cannot see any reason to provide the two filters if not used in the example, I feel like it adds more confusion then clarification. 
Also improved explanation a bit for the filters, let me know if it is not clear enough :+1:
=> Removed filter which were not exampled from doc

API.md, README.md, cli.js, lib/generator.js, package-lock.json, package.json, templates/html/.filters/all.js, templates/html/package-lock.json, templates/html/package.json, templates/java-spring/.filters/all.js, templates/java-spring/package-lock.json, templates/java-spring/package.json, templates/markdown/.filters/all.js, templates/markdown/package-lock.json, templates/markdown/package.json, templates/nodejs-ws/.filters/all.js, templates/nodejs-ws/.hooks/rename-package.js, templates/nodejs-ws/__package.json, templates/nodejs-ws/package-lock.json, templates/nodejs-ws/package.json, templates/nodejs/.filters/all.js, templates/nodejs/.hooks/rename-package.js, templates/nodejs/__package.json, templates/nodejs/package-lock.json, templates/nodejs/package.json
=> Convert templates in packages

AUTHORING.md, Dockerfile, templates/nodejs/.filters/all.js, templates/nodejs/config/common.yml, test/docs/streetlights.yml
Fixes #182 
- Updates docs for creating templates in area of hooks and partials
- Extends the test doc to have a server variable
- Adds support for variables in the `servers` object to the Node.js template. An example is based on the `port` variable
I could test MQTT protocol as it is already in the streetlights.yml. After my changes I generated the Nodejs example and started it. It received a message sent to `mqtt pub -t 'smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured' -h 'test.mosquitto.org' -p 1883 -m '{"id": 1"}'`
Important notes to how the `replaceVariablesWithValues` filter works:
- if variable is in URL but not declared, it stays
- if variable is in URL and declared, it picks up default, otherwise first enum element, otherwise is stays unchanged
It is …
=> Add support for server variables in Nodejs template

API.md, cli.js, lib/generator.js
We were installing the templates **only** when using the generator from the CLI and, therefore, it was breaking when using it as a library (e.g., in the playground).
This PR moves the installation process out of the `cli.js` file so it's available in both worlds.
=> Fix template installation when using generator as a library

package-lock.json, package.json
A few minutes ago, I [released a new version](https://github.com/asyncapi/parser-js/releases/tag/v0.14.0) of the JS parser. I'm updating it here too.
=> Bump parser version

lib/generator.js, package-lock.json, package.json
After [extracting RAML and OpenAPI schema parsers](https://github.com/asyncapi/parser-js/pull/44) from the JS parser, we must register them explicitly now.
=> Register optional schema parsers

Dockerfile, README.md
I changed the nodejs version in the Dockerfile to 12.16.1 (the current version 12 in Docker Hub) and I changed the version in the README requirements section to that version.
This allows template writers to use JavaScript E6 features such as classes.
Slack discussion: https://asyncapi.slack.com/archives/CQVJXFNQL/p1583949648004600?thread_ts=1583869811.002400&cid=CQVJXFNQL
=> Updated nodejs version.

package.json
- add info that package is public for releases to npm. Otherwise the first release with new scoped package fails
=> feat: add info that package is public for releases to npm

.travis.yml
- This PR remove not needed travis configuration as releases go through GitHub Actions now
This PR must be merged as fix to release PATCH release. The reason is that previous release was affected due to active travis and after 0.34, the 0.33 was created as is now visible as latest, and cannot be removed.
=> fix: remove travis config

README.md
- fix name of the package in install instructions
=> docs: fix name of the package in install instructions

lib/utils.js
Generator could not work propery in CI-like environment where all had to be installed from scratch. The npmi package as a result of installation returns an array of installed package. When you try it out locally and it can use local cache and node_modules, it always returns 1 element and this is why picking first element of an array result worked. Thing is that in CI-like env where you have no modules and everything has to be downloaded from scratch, and additional dependencies installed, the result is more than 1 and main package is always the last element
```
> github-action-for-generator@0.0.2 start /Users/wookiee/Documents/sources/github-action-for-generator
> node lib/index.js
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fnodejs-template 1958ms
npm …
```
=> fix: pick always the last element from the list of installed packages

Dockerfile, README.md
There is a bug with the npm version (6.13.4) packaged with the latest stable Node.js version (12.16.1). So far, the only information I could find is to update to the latest npm version. See this comment here: https://github.com/npm/cli/issues/613#issuecomment-578528618.
I also updated the Docker usage on the README.
Fixes #269
=> fix: resolves "invalid bin entry for package" bug

lib/generator.js
This makes the generator assume that from now the template files are located inside a folder called `template`. This way, the template files that should end up in the output directory are not mixed with the package details, i.e. package.json, package-lock.json, node_modules, .git, README.md (the usage README not the resulting one), .gitignore, etc.
Fixes #230
* See https://github.com/asyncapi/nodejs-template/pull/5
**To do**
Create pull requests on every template.
=> feat: Move template files to their own directory

package-lock.json, package.json
Adds a missing dependency to package.json: mkdirp.
Fixes #262
=> fix: install missing mkdirp dep

cli.js, package-lock.json, package.json
Fixes a bug with `mkdirp` that was introduced in the last release. I took the opportunity to remove the dependency because it's not needed anymore now that we're on Node.js 12.
See #123
=> fix: mkdirp misuse

cli.js
I screwed it with the last release, again. fs.mkdir is not failing when the directory doesn't exist but it does fail when it already exists. Dumb! Anyway, I'm using fs.extra package that was already installed.
See #281
=> fix: mkdirp round 2

lib/generator.js, package-lock.json
It was creating a `node_modules` directory on the directory the command was executed. It's fixed now.
Fixes #289
=> fix: node_modules created on current dir

.npmrc, README.md, package.json
- Update readme with information about requirements
- Add `engines` to package.json that will result in blocking installation if the engine requirements are not fulfilled:
```bash
Lukaszs-MBP:generator wookiee$ npm install
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for @asyncapi/generator@0.36.3: wanted: {"node":">=12.16","npm":">=6.13.7"} (current: {"node":"11.15.0","npm":"6.7.0"})
npm ERR! notsup Not compatible with your version of node/npm: @asyncapi/generator@0.36.3
npm ERR! notsup Not compatible with your version of node/npm: @asyncapi/generator@0.36.3
npm ERR! notsup Required: {"node":">=12.16","npm":">=6.13.7"}
npm ERR! notsup Actual:   {"npm":"6.7.0","node":"11.15.0"}
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
=> fix: add strict engines restriction when installing generator and update readme

docs/api.md, lib/generator.js
If you're using the generator as a library, your application's `node_modules` will be different than the default `DEFAULT_TEMPLATES_DIR`. For instance:
```
my-app/node_modules/@asyncapi/generator/...
my-app/node_modules/@asyncapi/html-template/...
```
If I use the generator as a library in this scenario, `DEFAULT_TEMPLATES_DIR` would be `my-app/node_modules/@asyncapi/generator/` and using the `@asyncapi/html-template` would result in the template being installed as a sibling of the generator, like above. Therefore, using `getTemplateFile('@asyncapi/html', 'partials/content.html')` will result in an attempt to access the file `my-app/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/partials/content.html`, which is incorrect.
This PR lets you change the …
=> feat: add templatesDir option to getTemplateFile

docs/api.md, lib/generator.js
So far, it's been possible to pass the parameter `asyncApiFileLocation` to the `generateFromString` function. This was forwarded to the parser as `path`. However, the parser allows us to customize a bunch of stuff, not just the `path`. I'm opening this param to allow passing anything to the parser.
Replace the string value you were passing by an object containing the `path` property. For example:
```js
const generator = new AsyncAPIGenerator('@asyncapi/html-template', os.tmpdir(), {
entrypoint: 'index.html',
output: 'string',
forceWrite: true,
});
// Replace this:
// const html = await generator.generateFromString(myAsyncApiString, 'https://path-to-my-server.com/my-asyncapi.yaml');
// With this:
const html = await generator.generateFromString(myAsyncApiString, { path: …
```
=> feat: Add parserOptions parameter instead of file name

docs/authoring.md, lib/generator.js, package-lock.json, package.json
It allows template owners to specify which version range of the generator they support. For instance, if we find a `.tp-config.json` file with the attribute `"generator": ">=0.36.0 <=1.0.0"` and the current version of the generator is `1.5.0`, it should trigger an error.
The format of the `generator` config property is a string representing semantic versioning ranges. See [semver](https://www.npmjs.com/package/semver) for more details.
Partially solves #280
=> feat: add support for template-generator versioning requirements

package-lock.json, package.json
Updates parser to the latest version to include `Schema.deprecated()`.
=> fix: update parser

config/default.json, docs/authoring.md, lib/filtersRegistry.js, lib/generator.js, lib/utils.js, package.json
- support filters from an external library. New template config parameter is added, `filters` that accepts an array of libraries that you can additionally register as filters for your template.
- generator now reads any function and then registers it as a filter so it is easier to write functions for templates and test them
- extracted whole logic related to filters registration to a separate file as `generator.js` is super overwhelming so using the opportunity that I worked on filters I moved them out
How to test:
`./cli.js test/docs/streetlights.yml https://github.com/derberg/html-template/#use-filters-lib -o output --force-write`
Your templates will not work with the latest generator. In your template, in filter directory you need to refactor your functions to follow …
=> feat: support filters from external library

lib/generator.js
There is a bug with definition of `templateParams`
Use following hooks:
```js
module.exports = register => {
register('generate:before', generator => {
console.log(generator.templateParams);
});
};
module.exports = register => {
register('generate:after', generator => {
console.log("/////////////////////////////////");
console.log(generator.templateParams);
});
};
```
Run as
```bash
docker run --rm -it -v ../java-spring-template-my-fork:/app/my-fork -v $pwd/asyncapi.yml:/app/asyncapi.yml -v $pwd/output:/app/output asyncapi/generator -o ./output -p listenerConcurrency=5 -p listenerPollTimeout=4000 asyncapi.yml /app/my-fork --force-write
```
Output:
```bash
{}
//////////////////////////////////
{}
```
For details about fix and `enumerable` - …
=> fix: Add enumerable to template parameters

README.md, cli.js, lib/watcher.js, package-lock.json, package.json
- watcher now watches explicitly the location of the template specified by the user. Before it was watching location where the template was installed in the generator global location
```
/.../.nvm/versions/node/v12.16.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/nodejs-ws-template/output/src/api/index.js was changed
```
- watcher now by default ignores output directory
- watcher supports flow when you trigger generation with watcher in the root of the template
- bump chokidar to latest
Fixes #185
=> fix: watcher ignores output and regeneration in loop

lib/filtersRegistry.js, lib/hooksRegistry.js
- clear module cache each time hooks and filters are required
Resolves #204
=> fix: watcher not reloading changes done to local filters and hooks

docs/authoring.md, lib/generator.js, test/generator.test.js
- Now you as template author could define a default value for template properties. If user pass parameter value in start command, for sure, it will be used as value of parameter. 
- Tested with https://github.com/asyncapi/java-spring-template/pull/37
Resolves #339
=> feat: add default value for template parameters

lib/generator.js, test/generator.test.js
- show warning for wrong spelled params
Example:
```bash
ag asyncapi.yaml @asyncapi/html-template -p baseHef=/doc -o output
Warning: This template doesn't have following params: baseHef.
```
Resolves: #345
=> feat: show warning for wrong spelled params

README.md, cli.js, docs/api.md, lib/__mocks__/utils.js, lib/generator.js, lib/utils.js, package.json, test/generator.test.js
- new function exposed -> `generateFromURL`
- support in CLI so we can do `ag https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/streetlights.yml @asyncapi/html-template`
validation if path is filesystem path or url is very basic here, not based on any sophisticated regex but just using `url.parse`. Let me know if you think it is bad approach. I don't see a use case that someone uses this feature as a library and on a server passes relative path to fetch the file from the same server where the generator is running, I think it is always about fetching from different server (hostname)
Resolves #266
=> feat: fetching asyncapi file from server in cli and library

cli.js, docs/authoring.md, lib/__mocks__/templateConfigValidator.js, lib/__mocks__/utils.js, lib/generator.js, lib/templateConfigValidator.js, lib/utils.js, test/generator.test.js, test/templateConfigValidator.test.js
- `.tp-config.json` is removed and config should be now done under `generator` props in the `package.json` file
- linter didn't like `validateTemplateConfig` as too complex function. Because I was working on config here so I took the liberty to refactor it and move to a separate file + add tests that cover every validation option
**MIGRATION**
This is a breaking change. Migrate by removing current config file and moving its content to `package.json` and bumping version of supported generator to the one released with this PR.
Example -> https://github.com/asyncapi/nodejs-template/pull/15
Resolves #228
=> feat: move template config to package.json

lib/templateConfigValidator.js, package-lock.json, package.json, test/templateConfigValidator.test.js
- generator will provide a hint to a user about most likely parameter name
Usage
```bash
ag asyncapi.yaml @asyncapi/html-template -p baseHef=/doc -o output
Warning: This template doesn't have following params: baseHef.
Did you mean "baseHref"?
```
Resolves: #351
=> feat: suggest possible correct parameter name

lib/templateConfigValidator.js, test/templateConfigValidator.test.js
- by default `sort()` takes number into string, so in case 3 and 11, 11 is first. I added custom sort comparison and extended tests
=> fix: sorting issue for suggested params

.github/templates-list-validator/action.yml
- Templates list checker fails as I did not provide `action.yml`. I forgot it is also needed for actions that are not going to the marketplace
=> refactor: add missing config for templates list checker

cli.js, lib/__mocks__/utils.js, lib/generator.js, lib/utils.js, test/generator.test.js
This is a very small change. As the cli instantiates a new `Generator` object with the given parameters, it uses `forceInstall` as the option to install the given template or not. But in the generator file the constructor definition it's done by deconstructing the third argument and the argument for installing the template is `forceInstall` not `install`.
So, no matter if you specify you want to install the template, `Generator.install` is always `false`.
I could've modified all the matches to `forceInstall` to make it clear you want to force the installation of the template, but I don't know if that's the case - as `forceWrite` is indeed forcing to write the changes. I better modified a single line to make the `forceInstall` option to be just `install`.
I noticed this "failed" silently …
=> fix: update cli Generator forceInstall parameter to install

.npmignore, README.md, lib/templateConfigValidator.js, package-lock.json, package.json
- this is chore PR as rc2 must be pushed manually, I will not do it until this is not merged
- allowing prerelases with this merge
rc1 doesn't work
`Error: This template is not compatible with the current version of the generator (1.0.0-rc.1). This template is compatible with the following version range: >=0.50.0 <2.0.0.`
=> chore: generator templates support prereleases

lib/generator.js
Since we're using npm to install templates, files like `.gitignore` and `.npmignore` are never downloaded (that's npm behavior we can't change).
Therefore, the only solution is to have templates rename `.gitignore` and `.npmignore` files to something different that npm will not understand. I chose `{.gitignore}` and `{.npmignore}` respectively. It's now the job of the Generator to rename them to become `.gitignore` and `.npmignore`.
=> Rename {.gitignore} and {.npmignore}

README.md
Section "CLI usage with Docker" was unupdated referencing to a removed file. Updated to point to one of the still present samples.
Fixes #406
=> docs: Update reference to sample file in README.md

lib/watcher.js
This should fix SonarCloud issue:
`Defining a function inside of a loop can yield unexpected results. Such a function keeps references to the variables which are 
defined in outer scopes. All function instances created inside the loop therefore see the same values for these variables, which is 
probably not expected.`
#416
=> refactor: Moved function from watcher before the for loop (#416)

Dockerfile, README.md
- Adjusted the Dockerfile so that it uses the official npm package instead of building from local source code.
- Updated the README accordingly (+ found a small inconsistency in a code example for the cli)
Resolves #399
=> refactor: Use official release in Dockerfile instead of sources

Dockerfile
- add chromium to docker for html-template
Fixes https://github.com/asyncapi/html-template/issues/112
=> chore: add chromium to docker for html-template

README.md, cli.js, lib/generator.js, package-lock.json, package.json, test/generator.test.js
- Extend `--disable-hook` flag to disable specific hook function(s). Example usage:
```text
--disable-hook generate:before generate:after=foo,bar
```
then generator will disable all hooks of `generate:before` type and `foo`, `bar` hooks of `generate:after` type.
However, the logic in the code overrides previous values for given type, so using flag such as: `--disable-hook generate:before generate:before=foo,bar` disables only `foo`, `bar` hooks of `generate:before` type, not whole type.
- update Readme.md
- update tests
Resolves https://github.com/asyncapi/generator/issues/333
=> chore: disable specific hook function(s)

.github/workflows/bump.yml, package.json
- add new bump workflow
- add get package name script
- so far looks like the generator will be bumped only in playground and github action for generator, which makes sense.
Approve this first https://github.com/asyncapi/github-action-for-generator/pull/18
See also https://github.com/asyncapi/.github/issues/16
=> ci: add workflow that bumps generator in other asyncapi repos

lib/generator.js, lib/utils.js
As in title: copy all non-JS files in the React render engine by default. Problem is described in the #466 issue:
> At the moment the Generator in the React case doesn't copy non-JS files in template, but skipped them. Workaround is add files to `nonRenderableFiles` array in configuration of template in `package.json`, but for template like https://github.com/asyncapi/nodejs-template/tree/master/template it isn't cool and has big impact to development: Each non-JS file must be added manually to an array.
Also if someone doesn't want render some `.js` file then can include it inside `nonRenderableFiles` array.
Resolves #466
=> fix: copy non-JS files in the React templates by default

cli.js, lib/generator.js, lib/watcher.js
This PR contains ignoring `__transpiled` folder inside template package in watch mode. It is ignored both in React and Nunjucks, because I don't see any objections why we should ignore it only in React - prefix `__` indicates that this folder is `special`.
Resolves #465
=> fix: ignore __transpiled folder in watch mode

README.md, package.json
=> fix: remove restriction to node<15 and npm<7 to enable testing on newer versions

docs/authoring.md, lib/renderer/react.js, package-lock.json, package.json, test/renderer.test.js, test/test-project/test-project.test.js
- Render an array of File component from React render engine - file templates feature.
- Add documentation for new feature.
- Add unit tests for React.
- Increase timeout in tests to 2m :(
Docs part:
The above way of rendering **file templates** works for both `nunjucks` and `react` render engine, but `react` also has another, more generic way to render multiple files. It is enough to return an array of `File` components in the rendering component. Check example:
```tsx
export default function({ asyncapi }) {
return [
<File name={`file1.html`}>Content</File>,
<File name={`file2.html`}>Content</File>
]
}
```
Part of https://github.com/asyncapi/generator-react-sdk/issues/10
=> feat: file-templates as array in React render engine

docs/authoring.md, lib/filtersRegistry.js, lib/utils.js, package-lock.json
Add support for asynchronous filters in Nunjucks:
- check before saving filter to registry that function is asynchronous, if yes, add as third argument to `addFilter` function `true` - it indicates that to filter should be always added callback with signature `callback(err, result)`.
- update docs with example.
In Nunjucks docs we can read:
Resolves https://github.com/asyncapi/generator/issues/515
=> feat: add support for asynchronous filters in Nunjucks

docs/authoring.md, lib/generator.js, lib/hooksRegistry.js, lib/renderer/react.js, lib/utils.js, package-lock.json, package.json
Add TypeScript supports in hooks and Nunjucks's filters:
- this PR only enables TS support for hooks/filters. Support for React will be added here https://github.com/asyncapi/generator-react-sdk/issues/3 
- code for TS is transpiling on-the-fly so developer doesn't have to transpile it before publishing to npm, but by this we must include `ts-node`, `typescript` and `source-map` packages in generator.
- add docs with general assumptions for using TS in hooks/filters.
Resolve https://github.com/asyncapi/generator/issues/455
=> feat: add TypeScript support for hooks and filters 

.github/workflows/release-docker.yml
The release workflow for docker picked a tag name from package.json version while it was not yet updated with latest version. This is why when we were releasing 0.2.0, it was released under tag indicating it is 0.1.0
Now we pick up release tag from release even as we already do in other workflows https://github.com/asyncapi/asyncapi-react/blob/master/.github/workflows/release-wc-and-playground.yml#L37
I only had to make sure we alwasy remove `v`. It was not needed in other workflows as others do npm and `npm publish` removes `v` on its own
Fixes #577
=> fix: align version of docker tag with the version of released generator

lib/generator.js
As things stand before my change:
- The `generate()` method does not set `this.asyncapi`
- `generateFromString()` sets `this.asyncapi` then calls `generate()`
- `generateFromUrl()` and `generateFromFile()` both call `generateFromString()`
Therefore, `generate()` cannot function when called directly, yet the other methods work by virtue of `generateFromString()`. I simply moved the definition of `this.asyncapi` to the `generate()` method as it is the root of the other methods.
https://github.com/asyncapi/html-template/issues/252
=> fix: move definition of asyncapi to code path of all generate* methods.

README.md
C# template is not listed in the readme.
=> docs: add dotnet-nats-template to list of generators

lib/utils.js
Signed-off-by: Hasan Oezdemir <21654050+nodify-at@users.noreply.github.com>
Fixes an issues caused indirectly by generator library which re-register the ts-node if ts-node called by ts-node-dev.
See: https://github.com/asyncapi/generator/issues/759
=> fix: do not register a ts-node if an env. variable with ts_node_dev is set 

.github/workflows/if-nodejs-release.yml
Release fails https://github.com/asyncapi/generator/actions/runs/3591963645/jobs/6047212449
We cannot release https://github.com/asyncapi/generator/pull/869 
CI got broken because of https://github.com/asyncapi/generator/pull/874 I let that happen, forgot to stop the bot for generator...
Eventually it will not be a problem once I fix https://github.com/asyncapi/.github/issues/172
`fix: ` because we need to trigger patch for https://github.com/asyncapi/generator/pull/869
=> fix: revert release workflow to working version

CODEOWNERS
- Changed the order of codeowner usernames in the CODEOWNERS file, so that only docs maintainers are pinged when documentation-related PRs are created.
- Reference [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
=> chore: change the order of codeowner usernames

docs/hooks.md
- This PR addressed the issue faced in the hooks.md page of the docs section in the main website
- Hyperlink: https://www.asyncapi.com/docs/tools/generator/hooks 
Resolves #941
=> docs: update links referring to configuration file

lib/generator.js
Previously, we're using `String` as the field type of `templateParams`, which was not correct, since we're bound to use `Object.keys()` on it and `Object.keys()` on string results on an array over the characters.
The different behaviors between `Object<string, string>`, `Object`, and `String` can be seen in this sandbox: https://codesandbox.io/s/bold-cache-r4tw43?file=/src/index.js.
Initially I wanted to go with just `Object` (as I mentioned on the issue), but apparently it accepts all kind of types, including string and numbers (which is wrong), so I went with `Record<string, string>`. Then, I saw the other object field types in the constructor and they are all using `Object<string, T>`, so I used that instead for consistency purposes. …
=> docs: fix JSDoc field for object parameter templateParams in Generator constructor

.github/workflows/update-maintainers.yml
This PR updates the MAINTAINERS.yaml file based on the changes made in the CODEOWNERS file. The workflow takes the repository name as input and adds it to the MAINTAINERS.yaml file.
When a new code owner is added, a corresponding maintainer object is created in the MAINTAINERS.yaml file with the repository name and the Twitter username of the code owner added to the object. It fetches the Twitter username using the GitHub API.
Similarly, when a code owner is removed, the corresponding maintainer object is removed from the MAINTAINERS.yaml file. The removal process checks if the maintainer has any other repositories before removing them from the MAINTAINERS.yaml file.
I have tested this workflow on my testRepo by adding a new code owner, and the MAINTAINERS.yaml file was …
=> ci: update MAINTAINERS.yaml based on CODEOWNERS changes

lib/parser.js, package-lock.json, package.json, test/parser.test.js
This PR updates `@smoya/multi-parser` to last version (`4.0.0`).
=> chore: update multi-parser to last version

lib/generator.js, package-lock.json
`generate` function refactored to smaller individual functions to reduce cognitive complexity
Related issue(s):
Fixes #1040
=> refactor: generate function refactored to reduce cognitive complexity

docs/configuration-file.md, lib/templateConfigValidator.js, package-lock.json, package.json, test/parser.test.js
This PR adds parser API v3 support to the generator and fixes a bug where if you ask for parser API v2, you get v3.
Related to https://github.com/asyncapi/html-template/issues/456
Blocked by https://github.com/smoya/multi-parser-js/pull/5
=> feat: add parser API v3 support

lib/generator.js
This PR https://github.com/asyncapi/generator/pull/1047/ broke feature that validates if output dir for generation points to directory with not staged changes
Related: https://github.com/asyncapi/cli/pull/908
=> fix: bring back git verification

docs/usage.md
This PR addresses a 404 link in the Generator docs that was reported in the following docs feedback post:
https://github.com/orgs/asyncapi/discussions/1080
=> docs: fix link that is giving 404 

docs/generator-template.md
- clarify paho-mqtt version in [this document](https://www.asyncapi.com/docs/tools/generator/generator-template)
- added missing double quote
See also #1145
=> docs: clarify paho version & fix typo

docs/usage.md
To reflect changes in asyncapi generate fromTemplate command for --watch option
Documentation update to follow `asyncapi generate fromTemplate --help`
=> docs: update usage doc with info about `--watch` flag and absence of `--version` flag

lib/generator.js
removed `asyncapiDocument.server(this.templateParams.server)` and used `asyncapiDocument.servers().get(this.templateParams.server)`
Fixes #1206
=> fix: refactor `asyncapiDocument.server()` to `asyncapiDocument.servers().get()` to fix `conditionalFiles`

.changeset/breezy-falcons-hammer.md, .github/workflows/release-docker.yml
Changes Added.
1. Removed the package name for the version tag. 
Related issue(s)
Related to: https://github.com/asyncapi/generator/issues/1044
=> fix: remove package name from version tag for Docker tagging

.changeset/breezy-falcons-hammer.md, .changeset/proud-brooms-accept.md, .github/workflows/release-docker.yml
Changes Added.
1. updated the default git context for docker.   
Related issue(s)
Related to: https://github.com/asyncapi/generator/issues/1044
=> fix: update the default context for docker publishing

apps/generator/lib/parser.js, apps/generator/package.json, package-lock.json
[@smoya/multi-parser](https://github.com/smoya/multi-parser-js) has been deprecated. Now its source code is included and released as part of https://github.com/asyncapi/parser-js monorepo.
=> chore: use @asyncapi/multi-parser instead of @smoya/multi-parser

.changeset/lemon-feet-fail.md, apps/generator/lib/generator.js, apps/generator/lib/utils.js, apps/generator/package.json, package-lock.json
- This PR removes `source-map-support` package which is not needed anymore.
Fixes #1067
=> fix: remove `source-map-support` package

.github/workflows/update-docs-in-website.yml, apps/generator/docs/model-generation.md
- Fixing docs update workflow, by correcting the path of docs file 
closes #1264
=> ci: docs update workflow fixed

apps/generator/docs/generator-template.md
While following the [generator template tutorial ](https://www.asyncapi.com/docs/tools/generator/generator-template) I found a minor fix to be done in docs.
After running the command `asyncapi generate fromTemplate test/fixtures/asyncapi.yml ./ -o test/project` the template files are  created in `test/project` folder instead of `output` folder as stated in docs.
N/A
=> docs: minor updation in generated files output folder path

.eslintrc, apps/generator/lib/generator.js, apps/nunjucks-filters/src/customFilters.js
Description
This pull request addresses the issue of unnecessary escape characters in the code.
Changes Made
Removed unnecessary escape characters (\$) from the fileName.replace statement:
=> refactor: switch to optional chaining in custom filters and update eslint config

.eslintrc, apps/generator/lib/parser.js
Description
refactored apps/generator/lib/parser.js mentioned in this [issue](https://sonarcloud.io/project/issues?fileUuids=AZB4seZIgviDxNeZYbJz&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sej0gviDxNeZYbKi&tab=code)
Changes Made-
used optional chaining to maintain readability.
=> refactor: optional chaining instead of expression in `parser.js`

apps/nunjucks-filters/src/index.js
Description
refactored apps/nunjucks-filters/src/index.js mentioned in this [issue](https://sonarcloud.io/project/issues?languages=js&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZD-TPs2DKL_zKkK1XuA)
Changes Made
Removed object assign and used object spread
related https://github.com/asyncapi/generator/issues/1272
=> refactor: use an object spread instead of `Object.assign` in filters

apps/generator/docs/api.md, apps/generator/lib/generator.js
Updating return statements of functions  `generateFromString`, `generateFromURL` and `generateFromFile` by adding type `TemplateRenderResult | undefined`
Fixes: #507
Screenshot of markdown rendered on website:
|Before|After|
|--------|--------|
|![image](https://github.com/user-attachments/assets/e53d2d72-dfcf-4b58-9cf6-d01344348179)|![Screenshot from 2025-01-11 14-30-34](https://github.com/user-attachments/assets/6fab5ff1-f22f-49e6-b911-0494ad73e338)|
cc: @derberg @ItshMoh
=> docs: jsdoc return statement update
