asyncapi/generator

lib/generator.js
templates/html/.helpers/handlebars.js
templates/markdown/.helpers/handlebars.js

Explained here: https://github.com/fmvilas/openapi3-generator/issues/6.

Inject Handlebars and Lodash

---

lib/generator.js

Remove hardcoded slashes

---

templates/markdown/.partials/message.md
templates/markdown/.partials/operation.md

Would be great to have a 0.3.2 release with these changes as it breaks my documentation. ;-)

Markdown: Removed/replaced closing tags that were never opened.

---

test/docs/streetlights.yml

It adds the Streetlights AsyncAPI example.

Add streetlights doc

---

.npmrc
.travis.yml

This will make Travis to auto-deploy to npm when pushing to master.

Auto-deploy to npm when pushing to master

---

templates/java-spring/.partials/AmqpConfig.java
templates/java-spring/.partials/MqttConfig.java

Removes handlebars if-statements and changes some conditions so topic, exchange and queue variables are no longer undefined.

fix(undefined-vars): [ISSUE-42] - Resolves issue #42.

---

lib/beautifier.js
templates/java-spring/.partials/AmqpConfig.java
templates/java-spring/.partials/MqttConfig.java
test/docs/sample.yml

- Added a map with subscribe-topics only to the beautifier. - Added a map with publish-topics only to the beautifier. - Removed if-statements that checked for topic type using maps instead. - Added x-service-name property to topics in ./test/docs/sample.yml

fix(comma-placement): [ISSUE-43] - Resolves issue #43

---

templates/html/.partials/content.html
templates/html/.partials/topics.html
templates/html/index.html

Based on https://github.com/asyncapi/docgen/issues/42

Hide the Topics block when no topic is describeed

---

README.md

Seems like there's an "s" missing here.

Typo in variable name

---

templates/html/.partials/schema-prop.html
test/docs/constraints.yml

A possible fix of https://github.com/asyncapi/generator/issues/57.

Added HTML rendering of minLength, maxLength and pattern.

---

README.md
cli.js

Add cli support template parameters

---

.dockerignore
Dockerfile
README.md
dockerboot.sh

Build with:
```sh
docker build -t asyncapi/generator .
```
Would be good to auto build and release this along with the npm releases.

Dockerfile for generator

---

package-lock.json
package.json
templates/markdown/.partials/info.md

Hello,
this is a fix for issue #75; it also removes a newline from the markdown template which irritated the chrome markdown viewer plugin.
Thanks for the great tool, btw!
br
Thomas.

fix for issue #75

---

Dockerfile
Makefile
README.md
dockerboot.sh

Fix Docker image

---

.eslintrc
API.md
AUTHORING.md
README.md
cli.js
lib/generator.js
package-lock.json
package.json
templates/html/.partials/sidebar.html
templates/nodejs/.editorconfig
templates/nodejs/.eslintrc
templates/nodejs/.filters/all.js
templates/nodejs/.tp-config.json
templates/nodejs/Dockerfile
templates/nodejs/README.md
templates/nodejs/__.gitignore
templates/nodejs/config/common.yml
templates/nodejs/package.json
templates/nodejs/src/api/adapters/amqp.js
templates/nodejs/src/api/adapters/mqtt.js
templates/nodejs/src/api/index.js
templates/nodejs/src/api/middlewares/buffer2string.js
templates/nodejs/src/api/middlewares/logger.js
templates/nodejs/src/api/middlewares/string2json.js
templates/nodejs/src/api/routes/$$channel$$.js
templates/nodejs/src/api/services/$$channel$$.js
templates/nodejs/src/lib/config.js
test/docs/streetlights.yml

This PR is about:
* Improving configuration files: it adds `supportedProtocols`, `requiredParams`, and `conditionalFiles`.
* Improves the way we pass params to templates from the CLI: before we were passing a JSON object with the `--params` modifier. The UX when typing JSON in the terminal is ugly. It's now changed to `--param name=value`. If you want to specify more than one param, you can just repeat it: `--param sidebarOrganization=byTags --param server=production` or using the short form `-p sidebarOrganization=byTags -p server=production`.
* Adds documentation of the API.
* Adds documentation for template authors.

Improve configuration files and CLI

---

lib/generator.js

Fix bug happening when template does not have conditional files

---

lib/generator.js

Fix bug preventing this.templatesDir from being populated

---

templates/nodejs-ws/.editorconfig
templates/nodejs-ws/.eslintrc
templates/nodejs-ws/.filters/all.js
templates/nodejs-ws/.hooks/create-asyncapi-file.js
templates/nodejs-ws/.hooks/rename-gitignore.js
templates/nodejs-ws/.tp-config.json
templates/nodejs-ws/Dockerfile
templates/nodejs-ws/README.md
templates/nodejs-ws/__.gitignore
templates/nodejs-ws/config/common.yml
templates/nodejs-ws/index.html
templates/nodejs-ws/package.json
templates/nodejs-ws/src/api/index.js
templates/nodejs-ws/src/api/routes.js
templates/nodejs-ws/src/api/services/$$channel$$.js
templates/nodejs-ws/src/lib/asyncapi.js
templates/nodejs-ws/src/lib/colors.js
templates/nodejs-ws/src/lib/config.js
test/docs/ws.yml

A new template to generate code for the WebSockets protocol using Node.js. Check out an example here: https://github.com/fmvilas/asyncapi-websockets-example.

Add nodejs-ws template

---

templates/nodejs-ws/index.html

Fix quotation on nodejs-ws help

---

templates/html/.partials/example.html
templates/html/.partials/message.html
templates/html/.partials/operation.html

Fixed [issue 111](https://github.com/asyncapi/generator/issues/111). 
- Pulled an example partial out of the message partial.
- Moved the right-block class to come after the center-block class.

Fixed the sidebar example issue

---

package-lock.json
package.json
templates/html/.filters/all.js

Fixes #116 
Fixed isExpandable filter as spotted by @joaoritter in #117.

Fix isExpandable filter in html template

---

templates/html/.partials/schema-prop.html

Fix required label on html template

---

templates/markdown/.partials/schema-prop.md

Fixes markdown table issue

---

lib/generator.js

Fixed the issue with unknown path for nunjucks for issue #145

Fixing unknown path

---

templates/html/.filters/all.js
templates/html/.partials/sidebar.html

Fixes #141
Fixes #148
Fixes #112

Fixed the issue with some channels might not have tags

---

templates/html/.partials/example.html
templates/html/.partials/operations.html
templates/html/.partials/schema-prop.html
test/docs/streetlights.yml

Fixing html template design issue

---

templates/html/.partials/introduction.html

Added support for contact information for the html template.

---

templates/html/.partials/operation.html

Partly fixes #100, still need to display query parameters.

Added parameter documentation

---

templates/html/.filters/all.js
templates/html/.partials/sidebar.html

Fixed issue with tags not being found.

---

lib/generator.js

Refactoring file separations

---

templates/html/.filters/all.js
templates/html/.partials/schema-prop.html
test/docs/streetlights.yml

Fixes https://github.com/asyncapi/generator/issues/136

HTML template: Facilitate Specification Extensions

---

lib/generator.js

fixes #166 
And should be backwards compatible.

Fixed problem with references.

---

templates/html/.filters/all.js
templates/html/.partials/example.html
templates/html/.partials/operation.html

Added fix to bug where examples in messages where not used correctly.

---

cli.js
lib/watcher.js
package-lock.json
package.json

Fixing watcher on linux

---

lib/generator.js

The parsed document is now exposed in the generator so that it can be referenced in hooks.

The parsed document is now exposed in the generator.

---

lib/generator.js
package-lock.json
package.json

Fixing not all messages, schema, parameters and security schemes are separated

---

API.md
templates/html/index.html

Hi,
I addressed #205, to be able to support subfolders in domains by setting templateParam
````
{  templateParams: {baseHref: '/async-docs/'} }
````
Best regards,
Stefan

#205 Adds baseHref param to index.html

---

AUTHORING.md
README.md
lib/generator.js
templates/html/.tp-config.json
templates/nodejs-ws/.tp-config.json
templates/nodejs/.tp-config.json

Add parameters to config file

---

API.md
README.md
cli.js
lib/generator.js
package-lock.json
package.json

Features:
- block generation if directory is a git repo and some changes are unstaged
- block generation if directory is not an empty directory
- add flag to force generation
- stuff not related to this issue https://github.com/asyncapi/generator/pull/223/files#diff-b58e2f1cee2acff55355343774e6d576R140 -> I changed it as when I wanted to learn what entrypoint is (was not clear for me after reading the docs) I noticed that it actually could not work as this was before `path.dirname(path.relative(this.templateDir), entrypointPath)` and `path.relative` requires 2 params
Fixes #180

Add feature to support git repos

---

.github/workflows/release.yml
package-lock.json
package.json

- add slack notification on new release
- fill be released as PATCH to test if it works properly

fix: add slack notification on new release

---

package.json

- fix package name and mardown rendering for slack plugin

chore: fix package name and mardown rendering for slack plugin

---

.eslintignore
.eslintrc
CONTRIBUTING.md
package-lock.json
package.json

- Add eslint to dev dep and have npm script for it
- Add eslint sonarjs plugin
See also #220

chore: improve eslint setup with sonarjs

---

docs/api.md
lib/generator.js
package-lock.json
package.json

- update dependency to new parser package

fix: update dependency to new parser package

---

.github/workflows/release.yml

- add docs generation to release pipeline so we do not have to remember about it on our own. Generated dosc will be pushed to repo with the same PR that will be created for package.json bump

chore: add docs generation to release pipeline

---

package-lock.json
package.json

Update the parser to get the latest features and fixes.

feat: Update parser to have the latest features and fixes

---

package-lock.json

Forgot to use conventional commits in my previous PR #299 🤦 
I'm taking advantage and updating package-lock.json 😄

feat: trigger release

---

lib/generator.js

fix: Fix generateFromFile

---

lib/generator.js

Adds some comments clarifying some behaviours on the `installTemplate` method.

chore: add comments on installTemplate method

---

README.md
cli.js
docs/api.md
lib/generator.js

- add debug flag to enable Nunjucks dev flag for more filter errors
See also #326. This PR is not solving linked issues yet as there is a pending discussion in Nunjucks.

feat: add debug flag to enable Nunjucks dev flag for more filter errors

---

.all-contributorsrc
.eslintignore
.github/templates-list-validator/README.md
.github/templates-list-validator/dist/index.js
.github/templates-list-validator/index.js
.github/templates-list-validator/package-lock.json
.github/templates-list-validator/package.json
.github/workflows/release.yml
.github/workflows/templates-list-validation.yml
.github/workflows/update-docs-on-docs-commits.yml
README.md
docs/api.md
lib/generator.js
package-lock.json
package.json

- add list of templates
- add toc
- add npx instruction
- add overview
- add more clarification on cli usage
- add contributors
- custom GH action that informs us that list of templates is outdated
- workflow that makes sure that bot updates API and TOC docs when there is a push of just `docs:` commit
TODO: if we go with list of templates, we need it also in tools on asyncapi website too
Resolves #285

docs: update readme with toc and list of templates

---

.github/templates-list-validator/index.js
README.md

- Add more love to the readme to have CLI options using also other tools than npm or node and npm

docs: improve readme toc structure

---

lib/templateConfigValidator.js
test/templateConfigValidator.test.js

- as discussed in slack params suggestions should also throw errors
It was super temptint to use loglevel on next level, like making installation and stacktrace silent when debug is of. Also wanted to try debug package. Buttttt that was getting to big so I removed all and kept the scope of this one related to params suggestions only 😄

feat: wrong params suggestions throw errors

---

.github/templates-list-validator/dist/index.js
.github/templates-list-validator/index.js

- forgot to rebuild yesterday the dist of the action 🤦

refactor: styling fix and dist gen for template action

---

.github/templates-list-validator/dist/index.js
.github/templates-list-validator/index.js

- Now proper readme file is read. I forgot that code executed in GitHub Action is not index.js from the root but the bundle from `dist` dir, which makes more nested dir structure. I added a comment to code so we do not forget in the future

chore: template list validation to read proper readme file

---

docs/authoring.md

Adds some docs that were missing on #380

docs: add docs about special file names

---

lib/generator.js
lib/utils.js
package.json
test/generator.test.js

We got hit by this issue again https://github.com/asyncapi/generator/pull/270. Sometimes there simply may be a problem with an installation that the main package is not last on the list because `devDependencies` are installed later. Now I made sure we always install only `dependencies` as there is no use case for the template to install `devDependencies`
As you can see I'm also bumping to rc.4 that we have to release once this is merged

chore: Make sure we get info about main installed package 

---

package-lock.json
package.json

- fix release candidate 5 with latest parser without re2
Fixes https://github.com/asyncapi/asyncapi/issues/416
Fixes https://github.com/asyncapi/website/issues/118

chore: fix release candidate 5 with latest parser without re2

---

lib/generator.js
package-lock.json
package.json

- new parser with fix for message function and avro schema parser
Fixes https://github.com/asyncapi/java-spring-template/issues/75

chore: new parser with fix for message function and avro schema parser

---

.npmignore
package-lock.json
package.json

- Bump dependency and package version

chore(release): Bump dependency and package version

---

.github/workflows/pull-request-testing.yml
.github/workflows/release.yml
README.md
package-lock.json
package.json

- Bump to use parser rc2 with circular refs support

chore(release): Bump to use parser rc2 with circular refs support

---

package-lock.json
package.json

- Bump generator to use latest parser release candidate

chore(release): Bump generator to use latest parser release candidate

---

.github/workflows/release.yml
package-lock.json
package.json

- bump version to rc 12 and improve release pipeline

chore(releasae): bump version to rc 12 and improve release pipeline

---

test/docs/dummy.yml

fix-issue-26, add parameters description at dummy.yml
See also https://github.com/asyncapi/html-template/issues/26

test: add description to parameter schema in dummy example

---

package-lock.json
package.json
test/docs/dummy.yml

- use first parser major release in rc 13

chore(release): use first parser major release in rc 13

---

docs/api.md
lib/generator.js

- Added short info on `asyncapi` object and `originalAsyncAPI` type 
- Generated documentation
Resolves #387

docs: update jsdoc for the generator

---

test/docs/dummy.yml

- add correlationId to dummy example

test: add correlationId to dummy example

---

test/docs/dummy.yml

- add example of required props to dummy file

test: add example of required props to dummy file

---

.github/workflows/pull-request-testing.yml
.github/workflows/release.yml
.github/workflows/update-docs-on-docs-commits.yml
Dockerfile
README.md
package-lock.json
package.json

- support node 14
- update deps
- I decided to not support npm 7 as it is in early release and not even bundled with node 14. The currently installed node is v14.15.0 and npm with it is v6.14.8
Fixes https://github.com/asyncapi/generator/issues/434

chore: support node 14 and update deps

---

test/docs/dummy.yml

- extend dummy example with array that has array in items
See also https://github.com/asyncapi/generator/issues/441

docs: extend dummy example with array that has array in items

---

package-lock.json
package.json

Tested it with an interactive tutorial on katacoda. Tested locally with latest template for templates. All looks good.
- bump 1.0.0
- latest parser 1.1.0
🚀 🍻 🥇

chore(release): 1.0.0 release :rocket:

---

package-lock.json
package.json

- use parser 1.1.1 that fixes channel names validation in the parser
See also https://github.com/asyncapi/parser-js/pull/196

fix: use parser 1.1.1 that fixes channel names validation in the parser

---

README.md

- add reference to template for generator templates

docs: add reference to template for generator templates

---

.github/workflows/pull-request-testing.yml

- improve pr testing workflow with a better name that is easier to identify
See also https://github.com/asyncapi/parser-js/pull/208

ci: improve workflow to test pull requests

---

docs/authoring.md

broken link to dummy file in authoring doc
Fixes #469

docs: broken link to dummy file in authoring doc

---

.eslintrc
package-lock.json
package.json
test/generator.test.js

- support testing on windows with unixify package
- silent linebreak linting
See also https://github.com/asyncapi/generator/pull/495/checks?check_run_id=1832629827

test: support testing on windows with unixify package

---

package-lock.json
package.json

- bump generator-react-sdk to 0.1.6
Fixes #498

fix: bump generator-react-sdk to 0.1.6

---

package-lock.json
package.json

This PR moves `chokidar` dependency which is required to run.

fix: move chokidar dev dependency

---

package-lock.json
package.json

This PR adds a simple integration test useful for CI which will ensure the generator works as a whole.
- Adds a new script called `test:integration`, which basically generates a test spec (Streetlights tutorial located at https://bit.ly/asyncapi) by using the `cli.js`.
- It runs the new `test:integration` script in the `test` script so the [CI workflow](https://github.com/asyncapi/generator/blob/master/.github/workflows/if-nodejs-pr-testing.yml) runs it on each PR.
The new test will catch dependency issues like https://github.com/asyncapi/generator/pull/510

ci: add simple integration test

---

lib/generator.js
lib/logMessages.js
lib/utils.js
package-lock.json
package.json
test/generator.test.js
test/test-project/test-global.test.js
test/test-project/test-project.test.js
test/utils.test.js

refactor: all the debug logs extracted to a new separate file

---

test/__snapshots__/integration.test.js.snap
test/docs/dummy.yml

Add some specification extensions samples to illustrate the extension rendering
Close #535
Here is the result :

docs(dummy): add specification extensions

---

test/__snapshots__/integration.test.js.snap
test/docs/dummy.yml

This specification evolution is useful to illustrate asyncapi/html-template#25

docs: add extra bindings to dummy.yml

---

test/docs/dummy.yml

Add to our dummy.yml file spec extension on a message level

test: extend dummy test file with spec extension in a message

---

test/__snapshots__/integration.test.js.snap
test/docs/dummy.yml
test/integration.test.js

This PR alters the dummy file to include an object property of type object with no properties and `additionalProperties` sat. 
related to https://github.com/asyncapi/markdown-template/pull/103

test: added property with no props but additionalProperties to dummy file

---

package-lock.json
package.json
test/__snapshots__/integration.test.js.snap
test/docs/dummy.yml

so far it is just parser 1.6 because 1.7 is not yet released, changes in dummy.yml are for now commented out

feat: use latest parser and support spec 2.1 validation

---

test/__snapshots__/integration.test.js.snap
test/docs/dummy.yml

- added example extension on channel level
- added more complex schema that was added recently to streetlight dummy example in react component

test(dummy): extend dummy example with channel extension and complex schema

---

lib/templateConfigValidator.js

refactor: added a statement for sort operation

---

README.md

Hi all and thank you for the warm welcome to the AsyncAPI community!
This PR is just to add the java-template to the list as we've recently moved it to the asyncapi organisation.

docs: add java-template to list

---

README.md

-Updated the broken links in readme file
Resolves #873

docs: broken links in readme file

---

docs/react-render-engine.md

Issue: https://github.com/asyncapi/generator/issues/910
Signed-off-by: Arya Gupta <arya.gupta99999@gmail.com>

docs: fix bugs in React render engine documentation

---

docs/template.md

- corrected the spelling of nodejs in template.md file
Fixes #919

docs: nodejs spelling correction

---

package-lock.json
package.json

fixes: https://github.com/asyncapi/generator/issues/962

fix: solve ajv errors

---

.github/workflows/update-docs-on-docs-commits.yml

Condition to check if the commit message starts with "docs:" to the "Generate docs and create PR" job, ensuring that the PR is created only when a commit with a message starting with "docs:" is made. 
**Related issue(s)** part of issue - https://github.com/asyncapi/cli/issues/123

ci: update generated parts of documentation based on 'docs:' commits"

---

lib/parser.js
package-lock.json
package.json

Add support for protbuf schema.
Solving #1033

feat: support protobuf

---

CODEOWNERS

I'm not feeling super comfortable with this PR but we have no choice. I tried to reach out to Pratik via email, linkedin, twitter and we pinged him multiple times on GH. I see he is active on GH but does not respond.
I assume Pratik got a job and cannot focus on AsyncAPI, which is completely fine. Just would be better if he opens this PR.
Anyway, @Florence-Njeri for now I've put myself next to your name for `.md` files, so there is someone who can approve changes in `.md` files that you will introduce. For others, I will definitely not approve and merge anything immediately without waiting for you.

chore: remove pratik2315 as a codeowner

---

.github/workflows/pr-testing-with-test-project.yml

- Changed command `docker-compose up` to `docker compose build`
**Related**
[Discussion #116610](https://github.com/orgs/community/discussions/116610)

ci: docker-compose command in PR testing with test project workflow

---

docs/template-context.md
docs/template-development.md
docs/template.md

Fix broken links to the documentation including the additional ones not included in the issue mentioned below.
Fixes #1184

docs: fix documentation links

---

.github/workflows/update-docs-in-website.yml

Fixed the path to generator docs at line 42
related to https://github.com/asyncapi/generator/issues/1264#issuecomment-2337884477

ci: minor fix in update docs workflow

---

apps/generator/lib/templateConfigValidator.js

In this PR I worked on this [issue](https://sonarcloud.io/project/issues?open=AZB4sejxgviDxNeZYbKh&id=asyncapi_generator)
captured test results [test-results.md](https://github.com/user-attachments/files/17333586/test-results.md)
**Resolved**
- Slightly improving readability
- Following modern JavaScript best practices

refactor: use optional chaining in template validator

---

apps/generator/lib/generator.js

In this PR I worked on this [issue](https://sonarcloud.io/project/issues?id=asyncapi_generator&open=AZB4sejpgviDxNeZYbKV)
captured test results [test-results.md](https://github.com/user-attachments/files/17333284/test-results.md)
**Resolve**
- Simplified Null Check
- Maintained functionality

refactor: use optional chaining in template params validation

---

apps/generator/test/renderer.test.js

In this PR I try to solve this [1st issue](https://sonarcloud.io/project/issues?impactSeverities=LOW&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sei0gviDxNeZYbKO) and [2nd issue](https://sonarcloud.io/project/issues?impactSeverities=LOW&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sei0gviDxNeZYbKP)
captured test results [test-results.md](https://github.com/user-attachments/files/17331010/test-results.md)
- unnecessary initialization.

refactor: simplify variable initialization in tests

---

apps/generator/lib/utils.js

I worked on this [issue](https://sonarcloud.io/project/issues?open=AZB4sekCgviDxNeZYbKk&id=asyncapi_generator)
captured test results [test-results.md](https://github.com/user-attachments/files/17398329/test-results.md)
- it make code easier to understand and read.

refactor: simplify `isAsyncFunction` function with optional chaining

---

apps/generator/lib/generator.js

- ...This PR addresses [issue](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sejpgviDxNeZYbKd)
- test results 
[test-results.md](https://github.com/user-attachments/files/17438752/test-results.md)

refactor: simplify `generateFile` function with optional chaining expression

---

apps/generator/docs/usage.md

- Updated the docs with html-template version and added `--use-new-generator` flag
fix #1322

docs: updated html-template version
